// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.27.3
// source: locale.proto

/* eslint-disable */
import { Metadata } from '@grpc/grpc-js';
import { Observable } from 'rxjs';

export const protobufPackage = 'locale';

export interface Locale {
  id: string;
  name: string;
}

export interface ListReq {
  orderBy?: Order | undefined;
}

export interface Order {
  sort?: string | undefined;
  order?: string | undefined;
  nulls?: string | undefined;
}

export interface ListRes {
  list: Locale[];
  totalCount: number;
}

export interface OneReq {
  id: string;
}

export interface OneRes {
  node: Locale | undefined;
}

export interface LocaleGrpcService {
  list(request: ListReq, metadata?: Metadata): Observable<ListRes>;
  one(request: OneReq, metadata?: Metadata): Observable<OneRes>;
}
